language: node_js
node_js:
- '6'
after_script:
- touch a.js
before_install:
- touch a.js
- ls
- openssl aes-256-cbc -K $encrypted_429b1cf1584d_key -iv $encrypted_429b1cf1584d_iv
  -in aliyun.enc -out ~\/.ssh/aliyun -d
